apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker_web_app
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: docker_web_app
  template:
    metadata:
      labels:
        app: docker_web_app
    spec:
      containers:
      - name: devops-webapp
        image: devops-webapp:latest 
        ports:
        - containerPort: 8080


