apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker_web_app
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: docker_web_app
  template:
    metadata:
      labels:
        app: docker_web_app
    spec:
      containers:
      - name: devops-webapp
        image: devops-webapp:latest 
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: docker-web-app-service
spec:
  selector:
    app: docker_web_app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
        
